export const countriesList = [
  'Canada',
  'United States',
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegowina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo, the Democratic Republic of the',
  'Cook Islands',
  'Costa Rica',
  'Cote d\'Ivoire',
  'Croatia (Hrvatska)',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'France Metropolitan',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard and Mc Donald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, Democratic People\'s Republic of',
  'Korea, Republic of',
  'Kuwait',
  'Kyrgyzstan',
  'Lao, People\'s Democratic Republic',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia, The Former Yugoslav Republic of',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia, Federated States of',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia (Slovak Republic)',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'Spain',
  'Sri Lanka',
  'St. Helena',
  'St. Pierre and Miquelon',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen Islands',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan, Province of China',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Virgin Islands (British)',
  'Virgin Islands (U.S.)',
  'Wallis and Futuna Islands',
  'Western Sahara',
  'Yemen',
  'Yugoslavia',
  'Zambia'
]

export const statesList = {
  'Canada': [ { name: 'Alberta', abbr: 'AB' }, { name: 'British Columbia', abbr: 'BC' }, { name: 'Manitoba', abbr: 'MB' }, { name: 'New Brunswick', abbr: 'NB' }, { name: 'Newfoundland and Labrador', abbr: 'NL' }, { name: 'Northwest Territories', abbr: 'NT' }, { name: 'Nova Scotia', abbr: 'NS' }, { name: 'Nunavut', abbr: 'NU' }, { name: 'Ontario', abbr: 'ON' }, { name: 'Prince Edward Island', abbr: 'PE' }, { name: 'Quebec', abbr: 'QC' }, { name: 'Saskatchewan', abbr: 'SK' }, { name: 'Yukon Territory', abbr: 'YT' } ],
  'United States': [
    { ' abbr': 'AL', 'name': 'Alabama' },
    { ' abbr': 'AK', 'name': 'Alaska' },
    { ' abbr': 'AZ', 'name': 'Arizona' },
    { ' abbr': 'AR', 'name': 'Arkansas' },
    { ' abbr': 'CA', 'name': 'California' },
    { ' abbr': 'CO', 'name': 'Colorado' },
    { ' abbr': 'CT', 'name': 'Connecticut' },
    { ' abbr': 'DC', 'name': 'Washington D.C.' },
    { ' abbr': 'DE', 'name': 'Delaware' },
    { ' abbr': 'FL', 'name': 'Florida' },
    { ' abbr': 'GA', 'name': 'Georgia' },
    { ' abbr': 'HI', 'name': 'Hawaii' },
    { ' abbr': 'ID', 'name': 'Idaho' },
    { ' abbr': 'IL', 'name': 'Illinois' },
    { ' abbr': 'IN', 'name': 'Indiana' },
    { ' abbr': 'IA', 'name': 'Iowa' },
    { ' abbr': 'KS', 'name': 'Kansas' },
    { ' abbr': 'KY', 'name': 'Kentucky' },
    { ' abbr': 'LA', 'name': 'Louisiana' },
    { ' abbr': 'ME', 'name': 'Maine' },
    { ' abbr': 'MD', 'name': 'Maryland' },
    { ' abbr': 'MA', 'name': 'Massachusetts' },
    { ' abbr': 'MI', 'name': 'Michigan' },
    { ' abbr': 'MN', 'name': 'Minnesota' },
    { ' abbr': 'MS', 'name': 'Mississippi' },
    { ' abbr': 'MO', 'name': 'Missouri' },
    { ' abbr': 'MT', 'name': 'Montana' },
    { ' abbr': 'NE', 'name': 'Nebraska' },
    { ' abbr': 'NV', 'name': 'Nevada' },
    { ' abbr': 'NH', 'name': 'New Hampshire' },
    { ' abbr': 'NJ', 'name': 'New Jersey' },
    { ' abbr': 'NM', 'name': 'New Mexico' },
    { ' abbr': 'NY', 'name': 'New York' },
    { ' abbr': 'NC', 'name': 'North Carolina' },
    { ' abbr': 'ND', 'name': 'North Dakota' },
    { ' abbr': 'OH', 'name': 'Ohio' },
    { ' abbr': 'OK', 'name': 'Oklahoma' },
    { ' abbr': 'OR', 'name': 'Oregon' },
    { ' abbr': 'PA', 'name': 'Pennsylvania' },
    { ' abbr': 'RI', 'name': 'Rhode Island' },
    { ' abbr': 'SC', 'name': 'South Carolina' },
    { ' abbr': 'SD', 'name': 'South Dakota' },
    { ' abbr': 'TN', 'name': 'Tennessee' },
    { ' abbr': 'TX', 'name': 'Texas' },
    { ' abbr': 'UT', 'name': 'Utah' },
    { ' abbr': 'VT', 'name': 'Vermont' },
    { ' abbr': 'VA', 'name': 'Virginia' },
    { ' abbr': 'WA', 'name': 'Washington' },
    { ' abbr': 'WV', 'name': 'West Virginia' },
    { ' abbr': 'WI', 'name': 'Wisconsin' },
    { ' abbr': 'WY', 'name': 'Wyoming' },
    { ' abbr': 'AS', 'name': 'American Samoa' },
    { ' abbr': 'GU', 'name': 'Guam' },
    { ' abbr': 'MP', 'name': 'Northern Mariana Islands' },
    { ' abbr': 'PR', 'name': 'Puerto Rico' },
    { ' abbr': 'UM', 'name': 'United States Minor Outlying Islands' },
    { ' abbr': 'VI', 'name': 'Virgin Islands' }
  ]
}

export const homeLocations = [
  'Please choose an option',
  'Winnipeg',
  'Calgary',
  'Steinbach',
  'Selkirk',
  'Inner City',
  'Canada',
  'International'
]
